import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import {
  MatButtonModule,
  MatCheckboxModule,
  MatSidenavModule,
  // MatMenuModule,
  // MatCardModule,
  // MatIconModule,
  // MatLineModule,
  // MatListModule,
  // MatSortModule,
  // MatTabsModule,
  // MatTreeModule,
  // MatBadgeModule,
  // MatChipsModule,
  MatInputModule,
  // MatRadioModule,
  // MatTableModule,
  // MatCommonModule,
  // MatDialogModule,
  // MatOptionModule,
  // MatRippleModule,
  // MatSelectModule,
  // MatSliderModule,
  // MatDividerModule,
  // MatStepperModule,
  MatToolbarModule,
  // MatTooltipModule,
  // MatGridListModule,
  MatSnackBarModule,
  // MatExpansionModule,
  // MatFormFieldModule,
  // MatPaginatorModule,
  MatDatepickerModule,
  // MatNativeDateModule,
  // MatBottomSheetModule,
  // MatProgressBarModule,
  // MatSlideToggleModule,
  // MatAutocompleteModule,
  // MatButtonToggleModule,
  // MatPseudoCheckboxModule,
  // MatProgressSpinnerModule
  MatNativeDateModule  

  } from '@angular/material';

@NgModule({
  declarations: [],
  imports: [
    CommonModule
  ],
  exports: [
    MatButtonModule,
    MatCheckboxModule,
    MatSidenavModule,
    MatNativeDateModule,
    // MatMenuModule,
    // MatCardModule,
    // MatIconModule,
    // MatLineModule,
    // MatListModule,
    // MatSortModule,
    // MatTabsModule,
    // MatTreeModule,
    // MatBadgeModule,
    // MatChipsModule,
    MatInputModule,
    // MatRadioModule,
    // MatTableModule,
    // MatCommonModule,
    // MatDialogModule,
    // MatOptionModule,
    // MatRippleModule,
    // MatSelectModule,
    // MatSliderModule,
    // MatDividerModule,
    // MatStepperModule,
    MatToolbarModule,
    // MatTooltipModule,
    // MatGridListModule,
    MatSnackBarModule,
    // MatExpansionModule,
    // MatFormFieldModule,
    // MatPaginatorModule,
    MatDatepickerModule,
    // MatNativeDateModule,
    // MatBottomSheetModule,
    // MatProgressBarModule,
    // MatSlideToggleModule,
    // MatAutocompleteModule,
    // MatButtonToggleModule,
    // MatPseudoCheckboxModule,
    // MatProgressSpinnerModule
  ],
  providers: [],
})
export class MaterialModule { }
